---
title: "Spatial GP Regression Model Visualization and Analysis"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(mgcv)
library(geoR)
library(ggplot2)
library(maps)
library(fields)
library(ggmap)
library(lubridate)
library(hms)
library(plotly)


wf_loc <- read.csv("/Users/abdullatifalnuaimi/Downloads/Wildland_Fire_Locations_US.csv")
ST_TX <- read.csv("/Users/abdullatifalnuaimi/Downloads/Texas_Fire_Department_and_Substations.csv")

wf_loc$Time_Spent_ONFIRE <- round(difftime(wf_loc$FireOutDate, wf_loc$FireDiscoveryDate, units = "days"), 2)
wf_loc$Time_Spent_ONFIRE_NUMERIC <- as.numeric(wf_loc$Time_Spent_ONFIRE)

wf_loc <- wf_loc[-which(wf_loc$Time_Spent_ONFIRE_NUMERIC < 0), ]

State = "TX"

wf_loc_TX <- wf_loc[which(wf_loc$State == State), ] 

wf_loc_TX_Wl <- wf_loc_TX[which(wf_loc_TX$FireCause == "Natural"), ]

df_spModel <- wf_loc_TX_Wl[,c('Longitude','Latitude','Time_Spent_ONFIRE_NUMERIC')]

# Defining dependent variables X = locations (lang,lat) and independent variable Y (time spent to put out fire)
Y<-df_spModel$Time_Spent_ONFIRE_NUMERIC
long=df_spModel$Longitude
lat=df_spModel$Latitude
Coords=cbind(long,lat)
X = Coords

# Separating the data set into 80% training and 20% testing
n = nrow(df_spModel)
n.testing = n*0.2
testing.id <- sample(1:n.testing,replace = FALSE)
Y.test <- Y[testing.id]
X.test <- X[testing.id,] 
coords.test <- Coords[testing.id,]

Y.train <- Y[-testing.id]
X.train <- X[-testing.id,] 
coords.train <- Coords[-testing.id,]

# Set in.sigma.sq to be a fraction of the residual var (Spatial variance)
ini.sigma.sq=0.9*(summary(lm(Y.train~X.train))$sigma)^2
## Set ini.phi to be a fraction of the maximum distance / 3 * any constant (Spatial range parameter) , here I choose 2
ini.phi = max(rdist(X.train))/(3*2)

 fit_mle <- likfit(data=Y.train,coords=coords.train,
            trend = ~ X.train[,1]+X.train[,2],
            fix.nugget=F,cov.model="exponential",ini = c(ini.sigma.sq,ini.phi))

 # Generate 2000 random Locations around Texas
Seqlat <- seq(from=25.50, to=36.30, by=.01)
Seqlong <- seq(from=-106.38, to=-93.31, by=.01)
Latitude <- sample(Seqlat, size=2000, replace=TRUE)
Longitude <- sample(Seqlong, size=2000, replace=TRUE)
VirtualCoordinates <- data.frame(x= Longitude, y = Latitude)
# We introduce maps library to make sure that all coordinates exactly inside Texas 
library(maps)
VirtualCoordinates$state <- map.where("state", VirtualCoordinates$x, VirtualCoordinates$y)
TX_VirtualCoordinates <- VirtualCoordinates[VirtualCoordinates$state == "texas" & !is.na(VirtualCoordinates$state) ,] 
# 500 random Locations inside Texas
TX_VirtualCoordinates_selected <-  TX_VirtualCoordinates[1:500,1:2]
X_New_Coordinates = TX_VirtualCoordinates_selected


krigecontrol=krige.control(type.krige = "OK", trend.d = ~ X.test[,1]+X.test[,2], trend.l = ~X_New_Coordinates[,1]+X_New_Coordinates[,2], obj.model = fit_mle)

prediction_New<-krige.conv(data=Y.test,coords=coords.test,locations=TX_VirtualCoordinates_selected,krig=krigecontrol)

# Converting any negative value to zero
prediction_New$predict <- replace(prediction_New$predict, which(prediction_New$predict < 0), 0)
# Rounding all numbers nearest integer
prediction_New$predict <- round(prediction_New$predict,digits=0)
# combining all the coordinates with predicted value
Predicted_data <- cbind(TX_VirtualCoordinates_selected,prediction_New$predict)

colnames(Predicted_data)[3] <- "Time_Spent_ONFIRE_Days"

#Introducing a background map Using Google map
register_google(key = "AIzaSyBTO-5cQCo2jsqXZzHBTX76dUnC0qvCF3s")
City="Texas"
map_google=get_map(location=City,zoom=6,maptype="hybrid",color="color")

# setting working directory
setwd("/Users/abdullatifalnuaimi/Downloads/Major_Rivers_dd83/")
# Uploading Shape files
library(rgdal)
shp <- readOGR(dsn = "." , layer = "MajorRivers_dd83")
#splitting shap files into data frame
df = fortify(shp)
# Plotting using ggplot2
ggplot()+
  geom_line(aes(x=long , y = lat , group = group), color = "lightblue" , data = df)

#Introducing a background map Using Google map
register_google(key = "AIzaSyBTO-5cQCo2jsqXZzHBTX76dUnC0qvCF3s")
City="Texas"
map_google=get_map(location=City,zoom=6,maptype="hybrid",color="color")

#png(file="/Users/abdullatifalnuaimi/Downloads/saving_plot2.png",
#width=600, height=350)
#dev.off()

#Output the map
# Plot modifications (http://www.sthda.com/english/wiki/ggplot2-point-shapes)

NFFS_Plot <- ggmap(map_google) + geom_point(aes(x = Longitude, y = Latitude ,color = "Natural Fire"), data = wf_loc_TX_Wl)+ geom_point(aes(x = Longitude, y = Latitude , color = "Fire Station") , data = ST_TX, size=1)+labs(title="Natural Fire VS Fire Stations",x ="Longitude", y = "Latitude") + theme(legend.position = "right")

Prediction_Plot <- ggmap(map_google) + geom_point(aes(x = x, y = y , color = Time_Spent_ONFIRE_Days ), data = Predicted_data) +labs(x ="Longitude", y = "Latitude") 

NFRD_Plot <- ggmap(map_google) + geom_point(aes(x = Longitude, y = Latitude ,color = Time_Spent_ONFIRE_NUMERIC), data = wf_loc_TX_Wl)+labs(title="Natural Fire (Real Data)",x ="Longitude", y = "Latitude") + theme(legend.position = "right")

FS_Plot <-  ggmap(map_google) +geom_point(aes(x = Longitude, y = Latitude ) , color = "skyblue2" , data = ST_TX, size=1)+labs(x ="Longitude", y = "Latitude")

WR_Plot <- ggmap(map_google) + geom_line(aes(x=long , y = lat , group = group), color = "lightblue" , data = df)+labs(x ="Longitude", y = "Latitude")

Mix_Plot <- ggmap(map_google) + geom_point(aes(x = Longitude, y = Latitude ,color = "Natural Fire"), data = wf_loc_TX_Wl)+ geom_point(aes(x = Longitude, y = Latitude , color = "Fire Station") , data = ST_TX, size=1)+ geom_line(aes(x=long , y = lat, color = "River Basins", group = group) , data = df)+labs(title="Texas Wildfire",x ="Longitude", y = "Latitude") 
```

Column {.tabset }
-----------------------------------------------------------------------

### Natural Fires (Prediction on 500 Random Locations)

```{r}
ggplotly(Prediction_Plot)
```


### Texas Fire Departments / Substations

```{r}
ggplotly(FS_Plot)
```

### Texas Natural Water Resources 

```{r}
ggplotly(WR_Plot)
```
